env:
  es2021: true
  node: true
extends:
  - airbnb-base
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  {
    import/prefer-default-export: 0,
    import/extensions:
      ["error", "ignorePackages", { "js": "never", "ts": "never" }],
  }
settings:
  {
    import/resolver:
      {
        node: { paths: ["src"], extensions: [".js", ".jsx", ".ts", ".tsx"] },
        typescript: {},
      },
  }
