env:
  es2021: true
  node: true
  jest: true
extends:
  - airbnb-base
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  {
    max-len: 0,
    no-return-await: 0,
    no-unused-vars: ["error", { "argsIgnorePattern": "^_" }],
    import/prefer-default-export: 0,
    import/extensions:
      ["error", "ignorePackages", { "js": "never", "ts": "never" }],
    import/no-extraneous-dependencies:
      [
        "error",
        {
          "devDependencies": ["**/*.test.ts", "**/*.spec.ts", "**/*.faker.ts"],
        },
      ],
  }
settings:
  {
    import/resolver:
      {
        node: { paths: ["src"], extensions: [".js", ".jsx", ".ts", ".tsx"] },
        typescript: {},
      },
  }
