version: "3"

services:
  postgres:
    container_name: postgres
    restart: always
    image: icarorobertos/postgres-9.6-multiple-database:1.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: server,server_dev,server_test
    ports:
      - 5432:5432

  adminer:
    container_name: adminer
    restart: always
    image: adminer
    ports:
      - 8080:8080
